export interface UpsertRoleFormValues {
  roleName: string;
  name: string;
  description: string;
  permission: Record<string, any>;
}

// Permissions are populated from the selected role and the current company's
// plan feature tree. Keeping a hard-coded tree here caused removed/renamed
// backend keys to be submitted when role data was unavailable.
export const UPSERT_ROLE_INITIAL: UpsertRoleFormValues = {
  roleName: '',
  name: '',
  description: '',
  permission: {},
};

export const NAME_CONST = {
  chat: 'Chat',
  access: 'Access',
  TEAM_MESSAGE: 'Team Message',
  DIRECT_MESSAGE: 'Direct Message',
  action: 'Actions',
  add: 'Add',
  edit: 'Edit',
  delete: 'Delete',
  reply: 'Reply',
  reaction: 'Reaction',
  upload_files: 'Upload Files',
  omni_channel: 'OMNI Channel',
  FACEBOOK: 'Facebook',
  add_team: 'Add team',
  WHATSAPP: 'Whatsapp',
  INSTAGRAM: 'Instagram',
  messages: 'Message',
  FAX: 'FAX',
  MMS: 'MMS',
  SMS: 'SMS',
  video: 'Video',
  CHAT: 'Chat',
  GRID_VIEW: 'Grid View',
  RECORDING: 'Recording',
  RAISE_HAND: 'Raise Hand',
  TEAM_INVITE: 'Team Invite',
  CONFERENCING: 'Conference',
  TRANSCRIPTION: 'Transcription',
  SCREEN_SHARING: 'Screen Sharing',
  USER: 'User',
  assign_number: 'Assign Number',
  is_call: 'Call',
  is_chat: 'Chat',
  SITE: 'Site',
  account_setting: 'Account Setting',
  billing: 'Billing',
  change_plan: 'Change Plan',
  request_plan: 'Request Plan',
  reports: 'Reports',
  call: 'Call',
  sms: 'SMS',
  note: 'Note',
  call_recording_listen: 'Call Recording Listen',
  call_report_permission: 'Call Report Permission',
  all: 'All',
  himself: 'Himself',
  team: 'Team',
  sms_report_permission: 'SMS Report Permission',
  settings: 'Settings',
  integration: 'Integration',
  ZOHO: 'Zoho',
  ZAPIER: 'Zapier',
  HUBSPOT: 'HubSpot',
  IVR: 'IVR',
  QUEUE: 'Queue',
  DEPARTMENT: 'Group',
  ANNOUNCEMENT: 'Announcement',
  phone_system_action: 'Phone System Action',
  POWER_DIALER: 'Power Dialer',
  PREDICTIVE_DIALER: 'Predictive Dialer',
  PROGRESSIVE_DIALER: 'Progressive Dialer',
  pause: 'Pause',
  summary: 'Summary',
  calling_rates: 'Calling Rates',
  virtual_numbers: 'Virtual Number',
  buy: 'Buy',
  view: 'View',
  release: 'Release',
  set_forwarding: 'Set Forwarding',
  update_forwarding: 'Update Forwarding',
  remove_forwarding: 'Remove Forwarding',
  advance_call_management: 'Advance Call Management',
  REALTIME: 'Realtime',
  TRANSFER: 'Transfer',
  CONFERENCE: 'Conference',
  monitoring: 'Monitoring',
  monitoring_features: 'Monitoring Features',
  barge: 'Barge',
  whisper: 'Whisper',
  intercept: 'Intercept',
  listen: 'Listen',
  hangup: 'Hangup',
  contact: 'Contact',
} as const;

export type NameConstKey = keyof typeof NAME_CONST;
